"""initial schema

Revision ID: 4cf412eecab4
Revises: 
Create Date: 2026-08-21 14:43:09.998396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cf412eecab4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('folders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_id IS NOT NULL OR owner_id IS NOT NULL', name='chk_root_owner'),
    sa.ForeignKeyConstraint(['book_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folders_parent_name')
    )
    op.create_index(op.f('ix_folders_book_id'), 'folders', ['book_id'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('sidebar_color', sa.String(length=16), nullable=False),
    sa.Column('text_color', sa.String(length=16), nullable=False),
    sa.Column('bg_color', sa.String(length=16), nullable=False),
    sa.Column('toolbar_color', sa.String(length=16), nullable=False),
    sa.Column('editor_color', sa.String(length=16), nullable=False),
    sa.Column('open_book_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('closed_folder_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('closed_chapter_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('book_order', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('book_collaborators',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('editor', 'viewer', name='book_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'user_id', name='uq_book_collaborators_book_user')
    )
    op.create_index(op.f('ix_book_collaborators_user_id'), 'book_collaborators', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('folder_id', sa.BigInteger(), nullable=False),
    sa.Column('book_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('notes_text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(name, '') || ' ' || coalesce(content_html, '') || ' ' || coalesce(notes_text, ''))", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'name', name='uq_chapters_folder_name')
    )
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_index(op.f('ix_chapters_folder_id'), 'chapters', ['folder_id'], unique=False)
    op.create_index('ix_chapters_search_tsv', 'chapters', ['search_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapters_search_tsv', table_name='chapters', postgresql_using='gin')
    op.drop_index(op.f('ix_chapters_folder_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_book_collaborators_user_id'), table_name='book_collaborators')
    op.drop_table('book_collaborators')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_book_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_table('users')
    # ### end Alembic commands ###
    # drop_table doesn't drop the Postgres ENUM type it depends on -- do it
    # explicitly or a downgrade-then-upgrade cycle fails with DuplicateObject.
    sa.Enum(name='book_role').drop(op.get_bind(), checkfirst=True)
